#!/bin/bash

echo "$@"

for file in $@
do
    dir=`dirname $file`

    lockdir="${dir}/PPstyle.lock"

    while :
    do
        if mkdir "$lockdir"
        then
            trap 'rm -rf "$lockdir"' 0

            format_linked=false

            if [ ! -f "$dir/.clang-format" ]; then
                ln -s "$(pwd)/PPstyle.format" "$dir/.clang-format"
                format_linked=true
            fi

            clang-format -i "$file"

            if $format_provided; then
                rm "$dir/.clang-format"
            fi

            rm -rf "$lockdir"

            break
        fi
    done
done
